log_dir: ././LogIX/Random-32*32
logging:
  cpu_offload: false
  flush_threshold: 1000000000
  log_dir: ././LogIX/Random-32*32
  log_dtype: none
  num_workers: 1
lora:
  init: random
  parameter_sharing: false
  parameter_sharing_groups: null
  rank: 32
project: ./LogIX/Random-32*32
root_dir: ./
