log_dir: ././LoGra/project/PCA-64*64
logging:
  cpu_offload: false
  flush_threshold: 1000000000
  log_dir: ././LoGra/project/PCA-64*64
  log_dtype: none
  num_workers: 1
lora:
  init: pca
  parameter_sharing: false
  parameter_sharing_groups: null
  rank: 64
project: ./LoGra/project/PCA-64*64
root_dir: ./
