log_dir: ././LoGra/project/PCA-32(U)
logging:
  cpu_offload: false
  flush_threshold: 1000000000
  log_dir: ././LoGra/project/PCA-32(U)
  log_dtype: none
  num_workers: 1
lora:
  init: pca
  parameter_sharing: false
  parameter_sharing_groups: null
  rank: 32
project: ./LoGra/project/PCA-32(U)
root_dir: ./
