log_dir: ./wiki
logging:
  cpu_offload: false
  flush_threshold: 1000000000
  log_dir: ./wiki
  log_dtype: none
  num_workers: 1
lora:
  init: random
  parameter_sharing: false
  parameter_sharing_groups: null
  rank: 64
project: wiki
root_dir: ./
