log_dir: ././LoGra/project/PCA-16*16
logging:
  cpu_offload: false
  flush_threshold: 1000000000
  log_dir: ././LoGra/project/PCA-16*16
  log_dtype: none
  num_workers: 1
lora:
  init: pca
  parameter_sharing: false
  parameter_sharing_groups: null
  rank: 16
project: ./LoGra/project/PCA-16*16
root_dir: ./
